### ISSUE TITLE
in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again.

### ISSUE THREAD

**Issue by haoisli9** [mauricef/WindowTabs#10]
in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again.
for example, when two documents name are abcbefghigklmn-20211221.docx and abcbefghigklmn-20211224.docx, if these two files are opened together, these two files will flash to each other until I close WindowTabs.
maybe it is an issue for check file handler?

Thanks.

**Comment by leafOfTree** [comment]
Hi @haoisli9. I tried Word with Microsoft 365 (Free Trial version) in Win10, but it seems to work well for me.
I created two files named `abcbefghigklmn-20211221.docx` and `abcbefghigklmn-20211224.docx` and opened them with Word. 

Maybe it only happens to a specific Word version. Can you share with me the Word version you use?

![image](https://user-images.githubusercontent.com/13349592/148628704-b76039b7-8948-4387-a458-0ae915a04ec3.png)

**Comment by haoisli9** [comment]
Hi.

    So glad recieving from you.
    I use win10 and office2019 professional. and I use simplified Chinese version. I find this problem in chinese file name, but this seems also happens in english file name.
    I only create two empty word file, like attachment. and I record the screen use powerpoint.
   I found this problem disappeared when I uncheck the autogroup option. but I like the autogroup function.
    I achived the test files and the powerpoint file in zip file. Please check, thanks again.



***@***.***
 
发件人： leaf
发送时间： 2022-01-08 12:43
收件人： mauricef/WindowTabs
抄送： haoisli9; Mention
主题： Re: [mauricef/WindowTabs] in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again. (Issue #10)
Hi @haoisli9. I tried Word with Microsoft 365 (Free Trial version) in Win10, but it seems to work well for me.
I created two files named abcbefghigklmn-20211221.docx and abcbefghigklmn-20211224.docx and opened them with Word.
Maybe it only happens to a specific Word version. Can you share with me the Word version you use?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoisli9** [comment]
Hi.

    In your screen, your word app seems not in maximum size. I found this problem only happen when word in maximum size.



***@***.***
 
发件人： leaf
发送时间： 2022-01-08 12:43
收件人： mauricef/WindowTabs
抄送： haoisli9; Mention
主题： Re: [mauricef/WindowTabs] in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again. (Issue #10)
Hi @haoisli9. I tried Word with Microsoft 365 (Free Trial version) in Win10, but it seems to work well for me.
I created two files named abcbefghigklmn-20211221.docx and abcbefghigklmn-20211224.docx and opened them with Word.
Maybe it only happens to a specific Word version. Can you share with me the Word version you use?
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leafOfTree** [comment]
I tried Word 2019 professional. But I still couldn't reproduce it even when in maximum size and with autogroup. Maybe we need to find out more about this issue.

By the way, I'm not able to find your attached zip files. Maybe you need to attach them again.

![image](https://user-images.githubusercontent.com/13349592/148677030-ca2d95fa-fade-40a1-81d6-c67eff7a5010.png)

**Comment by haoisli9** [comment]
The attached file is 3M, maybe it is too large. I send two test files in this letter, can you receive it ?

the screen-record file will be sent in another letter.



***@***.***
 
发件人： leaf
发送时间： 2022-01-09 17:42
收件人： mauricef/WindowTabs
抄送： haoisli9; Mention
主题： Re: [mauricef/WindowTabs] in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again. (Issue #10)
I tried Word 2019 professional. But I still couldn't reproduce it even when in maximum size and with autogroup. Maybe we need to find out more about this issue.
By the way, I'm not able to find your attached zip files. Maybe you need to attach them again.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoisli9** [comment]
the screen record file is attached in this letter. can you recieve it ?



***@***.***
 
发件人： leaf
发送时间： 2022-01-09 17:42
收件人： mauricef/WindowTabs
抄送： haoisli9; Mention
主题： Re: [mauricef/WindowTabs] in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again. (Issue #10)
I tried Word 2019 professional. But I still couldn't reproduce it even when in maximum size and with autogroup. Maybe we need to find out more about this issue.
By the way, I'm not able to find your attached zip files. Maybe you need to attach them again.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoisli9** [comment]
the wma file is about 4M, how large file can you receive? or do you have another mailbox that can recieve larger mail ?

thanks.



***@***.***
 
发件人： leaf
发送时间： 2022-01-09 17:42
收件人： mauricef/WindowTabs
抄送： haoisli9; Mention
主题： Re: [mauricef/WindowTabs] in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again. (Issue #10)
I tried Word 2019 professional. But I still couldn't reproduce it even when in maximum size and with autogroup. Maybe we need to find out more about this issue.
By the way, I'm not able to find your attached zip files. Maybe you need to attach them again.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leafOfTree** [comment]
It seems that you replied to the issue by email and sending files isn't supported yet. You can send files to countfornode@gmail.com directly.

**Comment by haoisli9** [comment]
Hi, I resend all the files to your gmail mailbox. please let me know if you received it.


Thanks.



***@***.***
 
发件人： leaf
发送时间： 2022-01-10 13:36
收件人： mauricef/WindowTabs
抄送： haoisli9; Mention
主题： Re: [mauricef/WindowTabs] in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again. (Issue #10)
It seems that you replied to the issue by email and sending files isn't supported yet. You can send files to ***@***.*** directly.
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoisli9** [comment]
I am so sorry that I found the flash issue is not windowtabs problem. Maybe it is conflect with some PC manager App. I closed Huawei PC Manager today and found it works.
    Another thing, I found when I change the "Fade out tabs on inactive windows" option, an assert raised. Can you check it?
    And Maybe you can change the version number, now it still shows 2018.7.20.

**Comment by leafOfTree** [comment]
I'm glad that you found it out.
I'll check the new one and consider changing the version number.
