### ISSUE TITLE
WindowTabs doesn't recognize PhotosApp.exe

### ISSUE THREAD

**Issue by AstudilloMarillo** [mauricef/WindowTabs#12]
@leafOfTree

I use your forked version of WindowTabs, but since you don't have an 'issues' page there, I will leave it here and hope you notice it/are willing to help. The Windows 10 default photos viewer app is not recognized by WindowTabs. It doesn't show up in the 'Programs' list in settings, and manually adding it to the .txt doesn't seem to work either. Different programs seem to detect this program differently, either as PhotosApp.exe or as ApplicationFrameHost.exe. Not sure which would be applicable to WindowTabs.

Would you be willing to try to fix this?

**Comment by leafOfTree** [comment]
Sure, I'll check it out.

**Comment by leafOfTree** [comment]
Please check the new release: https://github.com/leafOfTree/WindowTabs/releases/tag/v2023.10.15

Both Photo and Mail apps seem to be based on  ApplicationFrameHost.exe, causing them to be in the same group.
![Capture](https://github.com/mauricef/WindowTabs/assets/13349592/4d86fdae-1a00-4b7d-b93c-e0650c430026)

**Comment by AstudilloMarillo** [comment]
Just tried it, works great, thanks a lot!

I have one more question, is it possible to auto-group different applications together? Like say for example you'd want to automatically group 'Adobe Premiere Pro.exe' and 'Photoshop.exe'? I thought the Workspace tab could accomplish this, but I can't get it to work.

**Comment by AstudilloMarillo** [comment]
@leafOfTree I noticed you activated issues on your fork, so I'll move the remaining issue/request to over there for clarity.

https://github.com/leafOfTree/WindowTabs/issues/1
