### ISSUE TITLE
explorer shows an empty tab

### ISSUE THREAD

**Issue by haoisli9** [mauricef/WindowTabs#7]
Win10 OS, when I use windowtab to group explorer.exe, one empty tab always shown. and an empty item also in program listbar. How can I disable this empty tab?
Thanks. 
![windowtab](https://user-images.githubusercontent.com/17596774/102984396-7e11f500-4548-11eb-81f5-d6515587b6e8.png)

**Comment by leafOfTree** [comment]
Hey, you could check out my folk's fix https://github.com/leafOfTree/WindowTabs/commit/f42d206e8d9014ef90ebb39f5d71afa0b54a07da.

**Comment by haoisli9** [comment]
fixed，thanks a lot.

**Comment by haoisli9** [comment]
> Hey, you could check out my folk's fix [leafOfTree@f42d206](https://github.com/leafOfTree/WindowTabs/commit/f42d206e8d9014ef90ebb39f5d71afa0b54a07da).

fixed，thanks a lot.

**Comment by haoisli9** [comment]
fixed by leafOfTree@f42d206.

**Comment by haoisli9** [comment]
Hi, I found another issue for WindowTabs. Can you please review it?

in win10，when two docx's name are long and more similiar, windowTabs cause these two docx file flash again and again.
for example, when two documents name are abcbefghigklmn-20211221.docx and abcbefghigklmn-20211224.docx, if these two files are opened together, these two files will flash to each other until I close WindowTabs.
maybe it is an issue for check file handler?
Thanks.



***@***.***
 
From: leaf
Date: 2021-03-06 09:30
To: mauricef/WindowTabs
CC: haoisli9; Author
Subject: Re: [mauricef/WindowTabs] explorer shows an empty tab (#7)
Hey, you could check out my folk's fix ***@***.***

**Comment by leafOfTree** [comment]
Sure. I'll check it.

**Comment by leafOfTree** [comment]
Hi @haoisli9. I tried Word with Microsoft 365 (Free Trial version) in Win10, but it seems to work well for me.
I created two files named `abcbefghigklmn-20211221.docx` and `abcbefghigklmn-20211224.docx` and opened them with Word. 

Maybe it only happens to a specific Word version. Can you share with me the Word version you use?

![image](https://user-images.githubusercontent.com/13349592/148628704-b76039b7-8948-4387-a458-0ae915a04ec3.png)
